src/Itad2017/Models/Detail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Itad2017.Models
{
    public class Detail
    {
        public int ID { get; set; }
        public DateTime RegisterTime { get; set; }
        public bool IsConfirmed { get; set; }
        public string Code { get; set; }
        public string TshirtSize { get; set; }
        public bool IsPresent { get; set; }
    }
}

src/Itad2017/Models/Participant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;

namespace Itad2017.Models
{
    public class Participant
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Email { get; set; }
        public Detail Details { get; set; }

        
    }
}

src/Itad2017/Controllers/Old/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Itad2017.Data;
using Itad2017.Models;
using Microsoft.AspNetCore.Authorization;

namespace Itad2017.Controllers
{
    public class DetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DetailsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Details
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Detail.ToListAsync());
        }

        // GET: Details/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detail = await _context.Detail.SingleOrDefaultAsync(m => m.ID == id);
            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }

        // GET: Details/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,Code,IsConfirmed,IsPresent,RegisterTime,TshirtSize")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(detail);
        }

        // GET: Details/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detail = await _context.Detail.SingleOrDefaultAsync(m => m.ID == id);
            if (detail == null)
            {
                return NotFound();
            }
            return View(detail);
        }

        // POST: Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Code,IsConfirmed,IsPresent,RegisterTime,TshirtSize")] Detail detail)
        {
            if (id != detail.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetailExists(detail.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(detail);
        }

        // GET: Details/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detail = await _context.Detail.SingleOrDefaultAsync(m => m.ID == id);
            if (detail == null)
            {
                return NotFound();
            }

            return View(detail);
        }

        // POST: Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var detail = await _context.Detail.SingleOrDefaultAsync(m => m.ID == id);
            _context.Detail.Remove(detail);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DetailExists(int id)
        {
            return _context.Detail.Any(e => e.ID == id);
        }
    }
}

src/Itad2017/Controllers/Old/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Itad2017.Data;
using Itad2017.Models;
using Microsoft.AspNetCore.Authorization;

namespace Itad2017.Controllers
{
    public class ParticipantsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ParticipantsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Participants
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Participant.Include(n => n.Details).ToListAsync());
        }

        [Authorize]
        // GET: Participants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var detail = await _context.Detail.SingleOrDefaultAsync(m => m.ID == id);
            var participant = await _context.Participant.SingleOrDefaultAsync(m => m.ID == id);
            participant.Details = detail;
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participants/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Participants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,Email,FirstName,SecondName")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                _context.SaveNewParticipant(participant);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(participant);
        }

        // GET: Participants/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant.SingleOrDefaultAsync(m => m.ID == id);
            if (participant == null)
            {
                return NotFound();
            }
            return View(participant);
        }

        // POST: Participants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Email,FirstName,SecondName")] Participant participant)
        {
            if (id != participant.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipantExists(participant.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(participant);
        }

        // GET: Participants/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant.SingleOrDefaultAsync(m => m.ID == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participant.SingleOrDefaultAsync(m => m.ID == id);
            _context.Participant.Remove(participant);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ParticipantExists(int id)
        {
            return _context.Participant.Any(e => e.ID == id);
        }
    }
}

src/Itad2017/Views/Participants/Create.cshtml
@model Itad2017.Models.Participant

<style>
    body {
        background: url(http://i63.tinypic.com/25alqow.jpg);
    }
</style>
<div class="row abt-back-color" style="margin-top: 10vh;">
    <div class="col-md-4 col-md-offset-4">
        <section>
            <form asp-controller="Participants" asp-action="Create" method="post" class="form-horizontal">
                <h4 style="color: aqua;">Dodaj użytkownika</h4>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input asp-for="Email" class="form-control" placeholder="Email" />
                        <span asp-validation-for="Email" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input asp-for="FirstName" class="form-control" placeholder="Imię" />
                        <span asp-validation-for="FirstName" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input asp-for="SecondName" class="form-control" placeholder="Nazwisko" />
                        <span asp-validation-for="SecondName" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <a asp-area="" asp-controller="Participants" asp-action="Index" class="btn btn-default">wróć do listy</a>
                        <input type="submit" value="Dodaj Uczestnika" class="btn btn-default" style="background-color: aqua; color: black;" />
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Itad2017/Views/Participants/Delete.cshtml
@model Itad2017.Models.Participant

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Participant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Itad2017/Views/Participants/Details.cshtml
@model Itad2017.Models.Participant

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Participant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Itad2017/Views/Participants/Edit.cshtml
@model Itad2017.Models.Participant

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Participant</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SecondName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Itad2017/Views/Participants/Index.cshtml
@model IEnumerable<Itad2017.Models.Participant>

<style>
    body{
        background-color: #fff;
        color: #000000;
    }
</style>


@Html.Partial("~/Views/Shared/AdminPartials/_AdminMenu.cshtml")

<div class="container" ng-app="adminApp">
    <div ng-init='rawData = @Json.Serialize(Model) '></div>
    <div class="row" style="padding-top: 30px;" ng-controller="adminController as _model">
        <div class="col-sm-8">
            <h3>
                Zarejestrowane osoby
            </h3>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th style="color: #777;">
                            KOD
                        </th>
                        <th style="color: #777;">
                            Adres Email
                        </th>
                    </tr>
                    <tr>
                        <th style="color: #777;">
                            <input type="text" ng-model="search.details.code" />
                        </th>
                        <th style="color: #777;">
                            <input type="text" ng-model="search.email" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                <tr style="cursor: pointer;" ng-repeat="user in _model.people | filter: search" ng-click="_model.chooseOne(user)">
                    <td style="border: none; font-weight: bold;">
                        {{user.details.code}}
                    </td>
                    <td style="border: none;">
                        {{user.email}}
                        <span ng-if="user.details.isConfirmed == true"><i class="glyphicon glyphicon-ok text-success"></i></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            <h3>
                Szczegóły
            </h3>
            <div class="panel panel-primary">
                <div class="panel-body">
                    <div ng-if="choosenOne != null">
                        <button class="btn btn-link" ng-click="_model.clearDetails()" style="float: right;"><i class="glyphicon glyphicon-remove" aria-hidden="true"></i></button>
                        <center>
                            <h4>
                                {{choosenOne.details.code}}<br/>
                                <small>
                                    {{choosenOne.firstName}} {{choosenOne.secondName}}
                                </small>
                            </h4>
                        </center>
                        <p>
                            Koszulka <i style="float: right;">{{choosenOne.details.tshirtSize}}</i><br />
                            Data rejestracji <i style="float: right;">{{choosenOne.details.registerTime}}</i><br />
                            Id <i style="float: right;">{{choosenOne.id}}</i><br />
                            Adres email <i style="float: right;">{{choosenOne.email}}</i><br />
                        </p>
                        <hr/>
                        <a asp-action="Edit" asp-route-id="{{choosenOne.ID}}"><i class="glyphicon glyphicon-pencil" aria-hidden="true"></i> edytuj</a><br />
                        <a asp-action="Edit" asp-route-id="{{choosenOne.ID}}"><i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i> potwierdź obecność</a><br/>
                        <a asp-action="Edit" asp-route-id="{{choosenOne.ID}}"><i class="glyphicon glyphicon-gift" aria-hidden="true"></i> giftpack odebrany</a>
                        @*<a asp-action="Delete" asp-route-id="@item.ID" class="text-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>*@

                    </div>
                    <div ng-if="choosenOne == null">
                        <p class="text-danger">
                            nie wybrano użytkownika
                        </p>
                    </div>
                </div>
            </div>
            <h3>
                Dodaj uczestnika
            </h3>
            <div class="panel panel-primary">
                <div class="panel-body">
                    <form asp-controller="Participants" asp-action="Create" method="post">
                        <center>
                            <br />
                            <input name="Email" class="form-control" placeholder="Email" /><br />
                            <input name="FirstName" class="form-control" placeholder="Imię" /><br />
                            <input name="SecondName" class="form-control" placeholder="Nazwisko" /><br />
                            <input type="submit" value="Dodaj Nowego Uczestnika" class="btn btn-primary" /><br />
                        </center><br />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("~/Views/Shared/_customScripts.cshtml")

<script>
    var app = angular.module("adminApp", []);

    app.controller("adminController", ["$scope", function ($scope) {
        var self = this;

        console.log($scope.rawData);

        self.people = $scope.rawData;

        self.chooseOne = function (item) {
            $scope.choosenOne = item;
        };

        self.clearDetails = function () {
            $scope.choosenOne = null;
        };
    }]);
</script>